### ISSUE TITLE
Tick format doesn't work

### ISSUE THREAD

**Issue by startupleo2013** [jettro/c3-angular-directive#39] opened 2015-06-17 21:59 UTC
The directive: '<'chart-axis-x-tick tick-format="%Y-%m-%d %H" '/>', basically I want the time in following format other than default: '2015-06-10 04', but it doesn't work. I checked the source code and found it doesn't set 'config.data.xFormat', but only set 'config.axis.x.tick' (line 56), if I add the xFormat setting, it works well. Is it a bug or there is something I need to set?

**Comment by jettro** [comment] 2015-07-12 12:37
Please verify using the example in the project. There is an example with this code:
```
<c3chart bindto-id="chart-timeseries" chart-data="datapoints" chart-columns="datacolumns" chart-x="datax">
    <chart-axis>
        <chart-axis-x axis-id="x" axis-type="timeseries">
            <chart-axis-x-tick tick-format="%Y-%m-%d"/>
        </chart-axis-x>
    </chart-axis>
</c3chart>
```
When I change the tick-format to what you want it works for me. Are you using the latest version of the library? (0.5.2)

**Comment by didzis** [comment] 2015-09-14 13:11
The setting xFormat is format for input data parsing, but axis.x.tick.format is for displaying already parsed data. So, without setting xFormat it is not possible to parse date in custom format. Any possibilities to add that ?

**Comment by jettro** [comment] 2015-09-14 14:02
Not sure I completely understand what you mean, can you give me a sample that actually does not work? Using the mentioned example works for me, what am I missing.

**Comment by didzis** [comment] 2015-09-14 14:07
Let's assume he adds new datapoint with x value in format "2015-06-10 04". With x axis type timeseries and the default xFormat setting (which is, if not mistaken, "%Y-%m-%d") there will be a date parsing error. To fix this, xFormat needs to be set to "%Y-%m-%d %H", so the input data gets correctly parsed in a Date object. After that the date can be displayed on axis tick with specified format, which then can be the same or different, say, "%m-%d-%y".

**Comment by jettro** [comment] 2015-09-14 16:44
Aha, now I get it, I'll reopen the issue.

**Comment by didzis** [comment] 2015-09-14 17:58
Here https://github.com/jettro/c3-angular-directive/blob/master/src/axis-x-tick-directive.js#L151
is another issue: when type of x axis is timeseries, d3.time.format(...) should be used instead, but it seems, that with current design, it could be a little complicated to detect axis-type value from char-axis-x directive. One solution would be to move d3.format(...) and d3.time.format(...) to chart controller. This applies to y axis too, but more rarely.

**Comment by didzis** [comment] 2015-09-14 18:02
There seems to be an inconsistency with x and y format attribute names:
https://github.com/jettro/c3-angular-directive/blob/master/src/axis-y-tick-directive.js#L70
versus
https://github.com/jettro/c3-angular-directive/blob/master/src/axis-x-tick-directive.js#L149
The second one judging by documentation at the top of the same file, is a bug, it should be tickFormat as for y axis.

**Comment by marco-faustinelli** [comment] 2015-10-20 10:39
I have serious problems in getting _any_ formatting right for the x-axis timeseries.
Even the official example is not working for me on my machine. As you can see in the image that I am enclosing, the format says `.140, .141` rather than use Y-m-d.

This specific timeseries example is very much publicized, but it is **not** present in the live demo pages on the c3-angular site. Can you please point me to a live _working_ example page? I'd be most obliged, as I could then be able to check exactly which versions of the various libraries are needed to get all this straight.

![no_timeseries](https://cloud.githubusercontent.com/assets/8156006/10604697/86ced7e4-7726-11e5-9517-4a24eb8c750b.png)

**Comment by tamasgal** [comment] 2015-10-20 11:07
It's the same for me (i get negative, 3 digit numbers) . I ended up using an extra function for formatting:

    var time_format = function (timestamp) {
        return d3.time.format("%X")(new Date(timestamp));
    };

    <chart-axis-x-tick tick-rotate="50" tick-format-function="time_format" />

Which is of course only an intermediate solution…

**Comment by marco-faustinelli** [comment] 2015-10-20 12:50
Great workaround, @tamasgal. Thank you!
In the meantime I have found out that attribute `tick-format` is simply plainly **ignored** by the library code.

![no_tick_format_detection](https://cloud.githubusercontent.com/assets/8156006/10607242/83e37f0a-7738-11e5-93ed-e0dc41ca4726.png)

The `tickFormat` value is present in the object created by angular while parsing the HTML, but there are no lines of library code that care about it. Only `tick-rotate` and `tick-format-function` are managed.

This looks to me a plain old-fashioned _bug_, certainly it's no enhancement request: documentation talks about possibility to use `tick-format` but the code does not support it.

**Comment by marco-faustinelli** [comment] 2015-10-21 06:48
@tamasgal - after your kind clarifications offline, I have implemented inside the controller code my own series of formatting functions like:

    $scope.dDOTmDOTYFormattingFunction = function(t) { return d3.time.format("%d.%m.%Y")(new Date(t)); }

...and so on.

**Comment by mtzfactory** [comment] 2015-12-26 10:24
Hi,

I'm having the same issue, where should I put that function @tamasgal? Inside the controller, in an apart js...

thanks.

**Comment by jettro** [comment] 2016-01-01 12:41
This issue is becoming many issues in one. Going to extract multiple issues out of this one. Than I am closing this issue.

**Comment by jettro** [comment] 2016-01-01 13:42
Everything should be fine now. The example contains an example in the dynamic tab using time series. Going to close the issue, in case of problems feel free to let me know.

**Closed by jettro** 2016-01-01 13:42 UTC
Labels: bug

**Comment by 700m0nD** [comment] 2016-09-14 21:54
This does not appear to be fixed in version 1.3.1 or there is a regression. The formatting is off as in the case for @marco-faustinelli e.g. requesting for a formatting of `%Y-%m-%d` for a valid date object returns the `%H` instead which is 05 PM in my case. I had to resort to the workaround formatting function in this thread to get it to work. See the attached screenshot.

<img width="965" alt="screen shot 2016-09-14 at 2 32 11 pm" src="https://cloud.githubusercontent.com/assets/774868/18531408/10c7e2a2-7a8b-11e6-8846-bdeda6365c9e.png">

**Comment by josegranados** [comment] 2016-10-14 03:59
I confirm that the issue is still in 1.3.1, I have used a format function, the same workaround @tamasgal proposed.

**Comment by ptitdje45** [comment] 2016-10-26 09:09
Hi there, i am having this issue too with last version. So i have a question because i started with hottowel angular project and i can't use 'd3' as you all did for the workaround of @tamasgal. So how do i inject d3 to use it in my controller ?

**Comment by librien** [comment] 2018-06-18 20:50
Is this still unresolved?  I'm unable to even use the tick-format-function workaround.
